source_type: MySQL
sink_type: MySQL
source_config:
  - host: 127.0.0.1
    port: 3306
    username: XXXX
    password: XXXXXXXXXXXXXXXXXXXXXX
    database: XXXXXX
    # 默认 ssl_mode: disabled；如果源库必须使用SSL，可设置 ssl_mode: required
    table_name: "*"
    server_id: 10000

sink_config:
  - host: 127.0.0.1
    port: 3306
    username: XXXX
    password: XXXXXXXXXXXXXXXXXXXXXX
    database: XXXXXXXXXXXX
    # 默认 ssl_mode: disabled；如果目标库必须使用SSL，可设置 ssl_mode: required

sync_stored_view: true

plugins:
  - plugin_type: ColumnIn
    config:
      columns: is_deleted,is_delete
      values: 0,1

  - plugin_type: Plus
    config:
      columns: XXXXXX.id,XXXXXXXXXXXX.event_id
      plus: 10000000000
